import { StyleSheet } from "react-native";
import { COLORS } from "./theme";

export const globalStyles = StyleSheet.create({
    container: {
        padding: 20,
        paddingTop: 60,
        flex: 1,
        backgroundColor: COLORS.background,
      //  alignItems: 'center',
    },
    addWorkoutModalContainer: {
        flex: 1,
        backgroundColor: COLORS.background,
        paddingTop: 60,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    listContainer: {
        paddingBottom: 100,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        marginTop: 50,
        color: COLORS.text,
        textAlign: 'center',
    },
    item: {
        backgroundColor: COLORS.cardBackground,
        padding: 12,
        borderRadius: 8,
        width: '100%',
        minWidth: '100%',
        shadowColor: '#797878ff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        marginVertical: 10,
    },
    workoutName: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 4,
        color: COLORS.text,
    },
    workoutMode: {
        fontSize: 16,
        color: '#555',
        marginBottom: 10,
        color: '#cececeff',
    },
    exerciseText: {
        fontSize: 14,
        color: '#ffffffff',
        marginBottom: 2,
    },
    scoreText: {
        fontSize: 17,
        fontWeight: 'bold',     
        color: '#a3ffffff',
        marginBottom: 10,
    },
    tipText: {
        fontSize: 12,
        fontStyle: 'italic',
        color: '#c0c0c0ff',
        marginBottom: 2,
    },
    textContainer: {
        marginBottom: 20,
    },
    separator: {
        height: 10,
    },
    addButton: {
        backgroundColor: COLORS.accent,
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 20,
    },
    addButtonText: {
        color: COLORS.text,
        fontWeight: 'bold',
        fontSize: 16,
    },
    input: {
        backgroundColor: COLORS.inputBackground,
        borderColor: COLORS.border,
        borderWidth: 1,
        borderRadius: 8,
        padding: 10,
        color: COLORS.text,
        marginBottom: 10,
        width: '100%',
        alignSelf: 'stretch',
        height: 50,
        minWidth: '100%',
    },
    searchResultInput: {
        backgroundColor: COLORS.inputBackground,
        borderColor: COLORS.border,
        borderWidth: 1,
        borderRadius: 8,
        padding: 10,
        color: COLORS.text,
        marginBottom: 10,
        width: '80%',
        alignSelf: 'stretch',
        height: 50,
        minWidth: '80%',
    },
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: '90%',
        backgroundColor: COLORS.cardBackground,
        borderRadius: 10,
        padding: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
        textAlign: 'center',
        color: COLORS.text,
    },
    button: {
        flex: 1,
        marginHorizontal: 5,
        padding: 10,
        borderRadius: 8,
        alignItems: 'center',
        maxHeight: 40,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    cancelButton: {
        backgroundColor: '#ff5555ff',
    },
    saveButton: {
      backgroundColor: '#00cc99ff',
    },
    editButton: {   
        backgroundColor: COLORS.accent,
    },
    deleteButton: {
        backgroundColor: '#ff5555c0',
    },
    closeButton: {
        backgroundColor: 'gray',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    sectionLabel: {
        color: COLORS.text,
        fontSize: 16,
        fontWeight: 'bold',
        marginTop: 15,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLORS.background,
    },
    loadingText: {
        marginTop: 10,
        color: COLORS.text,
        fontSize: 16,
    },
    workoutDate: {
        fontSize: 16,
        color: '#555',
        marginBottom: 10,
        color: '#cececeff',
    },
    weightContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    calendarTheme: {
        backgroundColor: COLORS.background,
        calendarBackground: COLORS.background,
        textSectionTitleColor: COLORS.text,
        dayTextColor: COLORS.text,
        todayTextColor: COLORS.accent,
        selectedDayBackgroundColor: COLORS.accent,
        selectedDayTextColor: COLORS.background,
        dotColor: COLORS.accent,
        arrowColor: COLORS.accent,
        monthTextColor: COLORS.text,
        textMonthFontWeight: 'bold',
        textDisabledColor: '#555555',
        indicatorColor: COLORS.accent,
    },
    instructionText: {
        fontSize: 14,
        color: '#cccccc',
        textAlign: 'center',
        marginHorizontal: 20,
    },
    notFoundText: {
        fontSize: 16,
        color: COLORS.text,
        textAlign: 'center',
        marginTop: 20,
    },
    calendarInfo: {
        marginTop: 20, 
        padding: 15, 
        borderRadius: 10, 
        borderWidth: 1,
        borderColor: COLORS.border, 
        backgroundColor: COLORS.backgroundLight
    },
    calendarInfoText: {
        fontSize: 16,
        color: COLORS.text,
        textAlign: 'center',
        marginTop: 5,
        marginBottom: 5,
    }

})